-- MySQL Script generated by MySQL Workbench
-- 06/24/15 20:25:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cpv_dvfu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cpv_dvfu` ;
CREATE SCHEMA IF NOT EXISTS `cpv_dvfu` DEFAULT CHARACTER SET utf8 ;
USE `cpv_dvfu` ;

-- -----------------------------------------------------
-- Table `cpv_dvfu`.`volunteers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`volunteers` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`volunteers` (
  `VolunteerID` INT(11) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `MiddleName` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `DoB` DATE NOT NULL,
  `Gender` TINYINT(2) NOT NULL,
  `MobilePhone` VARCHAR(22) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Place` TEXT NOT NULL,
  `Job` TEXT NOT NULL,
  `Hobby` TEXT NOT NULL,
  `Stud` TEXT NOT NULL,
  `Social` INT NULL,
  `Size` VARCHAR(5) NULL,
  `Growth` INT(3) NULL,
  `WhyV` TEXT NOT NULL,
  `AdditionalInfo` TEXT NOT NULL,
  `VSchool` TINYINT(2) NULL,
  `Online` TINYINT(2) NOT NULL,
  `DateTimeReg` DATETIME NOT NULL,
  `DateTimeLastVisit` DATETIME NOT NULL,
  PRIMARY KEY (`VolunteerID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `MobilePhone` ON `cpv_dvfu`.`volunteers` (`MobilePhone` ASC);

CREATE UNIQUE INDEX `Email` ON `cpv_dvfu`.`volunteers` (`Email` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`volunactiv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`volunactiv` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`volunactiv` (
  `VolunteerID` INT(11) NOT NULL,
  `ActivityID` INT(11) NOT NULL,
  `DateTimeAct` INT NULL DEFAULT NULL,
  PRIMARY KEY (`VolunteerID`, `ActivityID`),
  CONSTRAINT `VolunteerID`
    FOREIGN KEY (`VolunteerID`)
    REFERENCES `cpv_dvfu`.`volunteers` (`VolunteerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ActivityID` ON `cpv_dvfu`.`volunactiv` (`ActivityID` ASC);

CREATE INDEX `DateTimeAct` ON `cpv_dvfu`.`volunactiv` (`DateTimeAct` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`organizers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`organizers` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`organizers` (
  `OrganizerID` INT(11) NOT NULL,
  `CompanyName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `MiddleName` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `DoB` DATE NULL,
  `Gender` TINYINT(2) NULL,
  `MobilePhone` INT(11) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Social` INT NULL,
  PRIMARY KEY (`OrganizerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`activities` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`activities` (
  `ActivityID` INT(11) NOT NULL,
  `OrganizeID` INT(11) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Place` TEXT NOT NULL,
  `Description` TEXT NOT NULL,
  `AdditionalInfo` TEXT NOT NULL,
  `DateTime` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ActivityID`, `OrganizeID`),
  CONSTRAINT `activities_ibfk_1`
    FOREIGN KEY (`ActivityID`)
    REFERENCES `cpv_dvfu`.`volunactiv` (`ActivityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `activities_ibfk_2`
    FOREIGN KEY (`OrganizeID`)
    REFERENCES `cpv_dvfu`.`organizers` (`OrganizerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `OrganizeID` ON `cpv_dvfu`.`activities` (`OrganizeID` ASC);

CREATE INDEX `DateTime` ON `cpv_dvfu`.`activities` (`DateTime` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`languages` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`languages` (
  `LanguageID` VARCHAR(12) NOT NULL,
  `LanguageName` VARCHAR(50) NOT NULL,
  `LanguageNative` VARCHAR(50) NOT NULL,
  `LanguageImage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`LanguageID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `UNIQUE` ON `cpv_dvfu`.`languages` (`LanguageName` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`activlang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`activlang` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`activlang` (
  `ActivityID` INT(11) NOT NULL,
  `LanguageID` VARCHAR(12) NOT NULL,
  `Level` INT(3) NOT NULL,
  PRIMARY KEY (`ActivityID`, `LanguageID`),
  CONSTRAINT `activlang_ibfk_2`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `cpv_dvfu`.`languages` (`LanguageID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `activlang_ibfk_3`
    FOREIGN KEY (`ActivityID`)
    REFERENCES `cpv_dvfu`.`activities` (`ActivityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `LanguageID` ON `cpv_dvfu`.`activlang` (`LanguageID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`volunlang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`volunlang` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`volunlang` (
  `VolunteerID` INT(11) NOT NULL,
  `LanguageID` VARCHAR(12) NOT NULL,
  `Level` INT(3) NULL DEFAULT '0',
  PRIMARY KEY (`VolunteerID`, `LanguageID`),
  CONSTRAINT `volunlang_ibfk_1`
    FOREIGN KEY (`VolunteerID`)
    REFERENCES `cpv_dvfu`.`volunteers` (`VolunteerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `volunlang_ibfk_2`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `cpv_dvfu`.`languages` (`LanguageID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `LanguageID` ON `cpv_dvfu`.`volunlang` (`LanguageID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`datetime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`datetime` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`datetime` (
  `id` INT NOT NULL,
  `DateStart` DATETIME NULL DEFAULT NULL,
  `DateEnd` DATETIME NULL DEFAULT NULL,
  `datetimeID` INT NOT NULL,
  PRIMARY KEY (`id`, `datetimeID`),
  CONSTRAINT `DateTimeAct`
    FOREIGN KEY (`datetimeID`)
    REFERENCES `cpv_dvfu`.`volunactiv` (`DateTimeAct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `datetimeID` ON `cpv_dvfu`.`datetime` (`datetimeID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`datetimeActivites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`datetimeActivites` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`datetimeActivites` (
  `ID` INT NOT NULL,
  `DateStart` DATETIME NULL DEFAULT NULL,
  `DateEnd` DATETIME NULL DEFAULT NULL,
  `datetimeID` INT NOT NULL,
  PRIMARY KEY (`ID`, `datetimeID`),
  CONSTRAINT `datetimeID`
    FOREIGN KEY (`datetimeID`)
    REFERENCES `cpv_dvfu`.`activities` (`DateTime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `datetimeID` ON `cpv_dvfu`.`datetimeActivites` (`datetimeID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
