-- MySQL Script generated by MySQL Workbench
-- 06/26/15 00:13:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cpv_dvfu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cpv_dvfu` ;
CREATE SCHEMA IF NOT EXISTS `cpv_dvfu` DEFAULT CHARACTER SET utf8 ;
USE `cpv_dvfu` ;

-- -----------------------------------------------------
-- Table `cpv_dvfu`.`Volunteers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`Volunteers` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`Volunteers` (
  `VolunteerID` INT(11) NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `MiddleName` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Hash` VARCHAR(255) NULL,
  `DoB` DATE NOT NULL,
  `Gender` VARCHAR(2) NOT NULL,
  `MobilePhone` VARCHAR(22) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Place` TEXT NOT NULL,
  `Job` TEXT NOT NULL,
  `Hobby` TEXT NOT NULL,
  `Stud` TEXT NOT NULL,
  `Social` VARCHAR(100) NULL,
  `Size` VARCHAR(5) NULL,
  `Growth` INT(3) NULL,
  `WhyV` TEXT NOT NULL,
  `AdditionalInfo` TEXT NOT NULL,
  `VSchool` TINYINT(2) NULL,
  `Online` TINYINT(2) NOT NULL,
  `DateTimeReg` DATETIME NOT NULL,
  `DateTimeLastVisit` DATETIME NOT NULL,
  PRIMARY KEY (`VolunteerID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `MobilePhone` ON `cpv_dvfu`.`Volunteers` (`MobilePhone` ASC);

CREATE UNIQUE INDEX `Email` ON `cpv_dvfu`.`Volunteers` (`Email` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`volunactiv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`volunactiv` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`volunactiv` (
  `VolunteerID` INT(11) NOT NULL,
  `ActivityID` INT(11) NOT NULL,
  `DateTimeVA` INT NULL,
  PRIMARY KEY (`VolunteerID`, `ActivityID`),
  CONSTRAINT `VolunteerID`
    FOREIGN KEY (`VolunteerID`)
    REFERENCES `cpv_dvfu`.`Volunteers` (`VolunteerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ActivityID` ON `cpv_dvfu`.`volunactiv` (`ActivityID` ASC);

CREATE INDEX `DateTimeVA` ON `cpv_dvfu`.`volunactiv` (`DateTimeVA` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`Organizers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`Organizers` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`Organizers` (
  `OrganizerID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrganizerName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `MiddleName` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Hash` VARCHAR(255) NULL,
  `DoB` DATE NULL,
  `Gender` VARCHAR(2) NULL,
  `MobilePhone` INT(11) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Social` VARCHAR(100) NULL,
  `DateTimeReg` DATETIME NULL,
  `DateTimeLastVisit` DATETIME NULL,
  PRIMARY KEY (`OrganizerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Email` ON `cpv_dvfu`.`Organizers` (`Email` ASC);

CREATE UNIQUE INDEX `MobilePhone` ON `cpv_dvfu`.`Organizers` (`MobilePhone` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`Activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`Activities` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`Activities` (
  `ActivityID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrganizeID` INT(11) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Place` TEXT NOT NULL,
  `Description` TEXT NOT NULL,
  `AdditionalInfo` TEXT NOT NULL,
  `DateTimeA` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ActivityID`, `OrganizeID`),
  CONSTRAINT `activities_ibfk_1`
    FOREIGN KEY (`ActivityID`)
    REFERENCES `cpv_dvfu`.`volunactiv` (`ActivityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `activities_ibfk_2`
    FOREIGN KEY (`OrganizeID`)
    REFERENCES `cpv_dvfu`.`Organizers` (`OrganizerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `OrganizeID` ON `cpv_dvfu`.`Activities` (`OrganizeID` ASC);

CREATE INDEX `DateTimeA` ON `cpv_dvfu`.`Activities` (`DateTimeA` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`Languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`Languages` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`Languages` (
  `LanguageID` VARCHAR(12) NOT NULL,
  `LanguageName` VARCHAR(50) NOT NULL,
  `LanguageNative` VARCHAR(50) NOT NULL,
  `LanguageImage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`LanguageID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `LanguageName` ON `cpv_dvfu`.`Languages` (`LanguageName` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`activlang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`activlang` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`activlang` (
  `ActivityID` INT(11) NOT NULL,
  `LanguageID` VARCHAR(12) NOT NULL,
  `Level` INT(3) NOT NULL,
  PRIMARY KEY (`ActivityID`, `LanguageID`),
  CONSTRAINT `activlang_ibfk_2`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `cpv_dvfu`.`Languages` (`LanguageID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `activlang_ibfk_3`
    FOREIGN KEY (`ActivityID`)
    REFERENCES `cpv_dvfu`.`Activities` (`ActivityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `LanguageID` ON `cpv_dvfu`.`activlang` (`LanguageID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`volunlang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`volunlang` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`volunlang` (
  `VolunteerID` INT(11) NOT NULL,
  `LanguageID` VARCHAR(12) NOT NULL,
  `Level` INT(3) NULL DEFAULT '0',
  PRIMARY KEY (`VolunteerID`, `LanguageID`),
  CONSTRAINT `volunlang_ibfk_1`
    FOREIGN KEY (`VolunteerID`)
    REFERENCES `cpv_dvfu`.`Volunteers` (`VolunteerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `volunlang_ibfk_2`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `cpv_dvfu`.`Languages` (`LanguageID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `LanguageID` ON `cpv_dvfu`.`volunlang` (`LanguageID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`datetime_volunactiv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`datetime_volunactiv` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`datetime_volunactiv` (
  `DT_VAID` INT NOT NULL AUTO_INCREMENT,
  `DateStart` DATETIME NULL DEFAULT NULL,
  `DateEnd` DATETIME NULL DEFAULT NULL,
  `DateTimeVAID` INT NOT NULL,
  PRIMARY KEY (`DT_VAID`, `DateTimeVAID`),
  CONSTRAINT `DateTimeAct`
    FOREIGN KEY (`DateTimeVAID`)
    REFERENCES `cpv_dvfu`.`volunactiv` (`DateTimeVA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `DateTimeVAID` ON `cpv_dvfu`.`datetime_volunactiv` (`DateTimeVAID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`datetime_Activites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`datetime_Activites` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`datetime_Activites` (
  `DT_AID` INT NOT NULL AUTO_INCREMENT,
  `DateStart` DATETIME NULL DEFAULT NULL,
  `DateEnd` DATETIME NULL DEFAULT NULL,
  `DateTimeAID` INT NOT NULL,
  PRIMARY KEY (`DT_AID`, `DateTimeAID`),
  CONSTRAINT `datetimeID`
    FOREIGN KEY (`DateTimeAID`)
    REFERENCES `cpv_dvfu`.`Activities` (`DateTimeA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `DateTimeAID` ON `cpv_dvfu`.`datetime_Activites` (`DateTimeAID` ASC);


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`Report` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`Report` (
  `ReportID` INT NOT NULL AUTO_INCREMENT,
  `NameActivity` VARCHAR(255) NULL,
  `DateActivityStart` DATE NULL,
  `DateActivityEnd` DATE NULL,
  `PlaceActivity` TEXT NULL,
  `DescriptionActivity` TEXT NULL,
  `FunctionVolunteers` TEXT NULL,
  `SumVolunteers` TEXT NULL,
  `Volunteers` TEXT NULL,
  `LevelActivity` VARCHAR(50) NULL,
  `Social` TEXT NULL,
  PRIMARY KEY (`ReportID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpv_dvfu`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cpv_dvfu`.`user` ;

CREATE TABLE IF NOT EXISTS `cpv_dvfu`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
